// Ülke adları, oyunda desteklenen her dil için ayrı çeviriyle tutulur.
// `kCountryLangOrder` içindeki sıra, her `CountryData.names` listesindeki
// sırayla birebir eşleşir.

typedef CountryData = (String code, String flag, List<String> names);

const List<String> kCountryLangOrder = [
  'en', 'tr', 'es', 'pt', 'de', 'fr', 'it', 'ru', 'ja', 'ko', 'pl', 'th', 'zh', 'ar', 'id',
];

const List<CountryData> kCountries = [
  ('AF', '🇦🇫', ['Afghanistan', 'Afganistan', 'Afganistán', 'Afeganistão', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Афганистан', 'アフガニスタン', '아프가니스탄', 'Afganistan', 'อัฟกานิสถาน', '阿富汗', 'أفغانستان', 'Afghanistan']),
  ('AL', '🇦🇱', ['Albania', 'Arnavutluk', 'Albania', 'Albânia', 'Albanien', 'Albanie', 'Albania', 'Албания', 'アルバニア', '알바니아', 'Albania', 'แอลเบเนีย', '阿爾巴尼亞', 'ألبانيا', 'Albania']),
  ('DZ', '🇩🇿', ['Algeria', 'Cezayir', 'Argelia', 'Argélia', 'Algerien', 'Algérie', 'Algeria', 'Алжир', 'アルジェリア', '알제리', 'Algieria', 'แอลจีเรีย', '阿爾及利亞', 'الجزائر', 'Aljazair']),
  ('AD', '🇦🇩', ['Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorre', 'Andorra', 'Андорра', 'アンドラ', '안도라', 'Andora', 'อันดอร์รา', '安道爾', 'أندورا', 'Andorra']),
  ('AO', '🇦🇴', ['Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Ангола', 'アンゴラ', '앙골라', 'Angola', 'แองโกลา', '安哥拉', 'أنغولا', 'Angola']),
  ('AG', '🇦🇬', ['Antigua & Barbuda', 'Antigua ve Barbuda', 'Antigua y Barbuda', 'Antígua e Barbuda', 'Antigua und Barbuda', 'Antigua-et-Barbuda', 'Antigua e Barbuda', 'Антигуа и Барбуда', 'アンティグア・バーブーダ', '앤티가 바부다', 'Antigua i Barbuda', 'แอนติกาและบาร์บูดา', '安地卡及巴布達', 'أنتيغوا وبربودا', 'Antigua dan Barbuda']),
  ('AR', '🇦🇷', ['Argentina', 'Arjantin', 'Argentina', 'Argentina', 'Argentinien', 'Argentine', 'Argentina', 'Аргентина', 'アルゼンチン', '아르헨티나', 'Argentyna', 'อาร์เจนตินา', '阿根廷', 'الأرجنتين', 'Argentina']),
  ('AM', '🇦🇲', ['Armenia', 'Ermenistan', 'Armenia', 'Armênia', 'Armenien', 'Arménie', 'Armenia', 'Армения', 'アルメニア', '아르메니아', 'Armenia', 'อาร์เมเนีย', '亞美尼亞', 'أرمينيا', 'Armenia']),
  ('AU', '🇦🇺', ['Australia', 'Avustralya', 'Australia', 'Austrália', 'Australien', 'Australie', 'Australia', 'Австралия', 'オーストラリア', '호주', 'Australia', 'ออสเตรเลีย', '澳大利亞', 'أستراليا', 'Australia']),
  ('AT', '🇦🇹', ['Austria', 'Avusturya', 'Austria', 'Áustria', 'Österreich', 'Autriche', 'Austria', 'Австрия', 'オーストリア', '오스트리아', 'Austria', 'ออสเตรีย', '奧地利', 'النمسا', 'Austria']),
  ('AZ', '🇦🇿', ['Azerbaijan', 'Azerbaycan', 'Azerbaiyán', 'Azerbaijão', 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaigian', 'Азербайджан', 'アゼルバイジャン', '아제르바이잔', 'Azerbejdżan', 'อาเซอร์ไบจาน', '亞塞拜然', 'أذربيجان', 'Azerbaijan']),
  ('BS', '🇧🇸', ['Bahamas', 'Bahamalar', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Багамы', 'バハマ', '바하마', 'Bahamy', 'บาฮามาส', '巴哈馬', 'باهاماس', 'Bahama']),
  ('BH', '🇧🇭', ['Bahrain', 'Bahreyn', 'Baréin', 'Bahrein', 'Bahrain', 'Bahreïn', 'Bahrein', 'Бахрейн', 'バーレーン', '바레인', 'Bahrajn', 'บาห์เรน', '巴林', 'البحرين', 'Bahrain']),
  ('BD', '🇧🇩', ['Bangladesh', 'Bangladeş', 'Bangladés', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'Bangladesh', 'Бангладеш', 'バングラデシュ', '방글라데시', 'Bangladesz', 'บังกลาเทศ', '孟加拉', 'بنغلاديش', 'Bangladesh']),
  ('BB', '🇧🇧', ['Barbados', 'Barbados', 'Barbados', 'Barbados', 'Barbados', 'Barbade', 'Barbados', 'Барбадос', 'バルバドス', '바베이도스', 'Barbados', 'บาร์เบโดส', '巴貝多', 'باربادوس', 'Barbados']),
  ('BY', '🇧🇾', ['Belarus', 'Belarus', 'Bielorrusia', 'Bielorrússia', 'Weißrussland', 'Biélorussie', 'Bielorussia', 'Беларусь', 'ベラルーシ', '벨라루스', 'Białoruś', 'เบลารุส', '白俄羅斯', 'بيلاروسيا', 'Belarus']),
  ('BE', '🇧🇪', ['Belgium', 'Belçika', 'Bélgica', 'Bélgica', 'Belgien', 'Belgique', 'Belgio', 'Бельгия', 'ベルギー', '벨기에', 'Belgia', 'เบลเยียม', '比利時', 'بلجيكا', 'Belgia']),
  ('BZ', '🇧🇿', ['Belize', 'Belize', 'Belice', 'Belize', 'Belize', 'Belize', 'Belize', 'Белиз', 'ベリーズ', '벨리즈', 'Belize', 'เบลีซ', '貝里斯', 'بليز', 'Belize']),
  ('BJ', '🇧🇯', ['Benin', 'Benin', 'Benín', 'Benin', 'Benin', 'Bénin', 'Benin', 'Бенин', 'ベナン', '베냉', 'Benin', 'เบนิน', '貝南', 'بنين', 'Benin']),
  ('BT', '🇧🇹', ['Bhutan', 'Bhutan', 'Bután', 'Butão', 'Bhutan', 'Bhoutan', 'Bhutan', 'Бутан', 'ブータン', '부탄', 'Bhutan', 'ภูฏาน', '不丹', 'بوتان', 'Bhutan']),
  ('BO', '🇧🇴', ['Bolivia', 'Bolivya', 'Bolivia', 'Bolívia', 'Bolivien', 'Bolivie', 'Bolivia', 'Боливия', 'ボリビア', '볼리비아', 'Boliwia', 'โบลิเวีย', '玻利維亞', 'بوليفيا', 'Bolivia']),
  ('BA', '🇧🇦', ['Bosnia & Herzegovina', 'Bosna Hersek', 'Bosnia y Herzegovina', 'Bósnia e Herzegovina', 'Bosnien und Herzegowina', 'Bosnie-Herzégovine', 'Bosnia ed Erzegovina', 'Босния и Герцеговина', 'ボスニア・ヘルツェゴビナ', '보스니아 헤르체고비나', 'Bośnia i Hercegowina', 'บอสเนียและเฮอร์เซโกวีนา', '波士尼亞與赫塞哥維納', 'البوسنة والهرسك', 'Bosnia dan Herzegovina']),
  ('BW', '🇧🇼', ['Botswana', 'Botsvana', 'Botsuana', 'Botsuana', 'Botsuana', 'Botswana', 'Botswana', 'Ботсвана', 'ボツワナ', '보츠와나', 'Botswana', 'บอตสวานา', '波札那', 'بوتسوانا', 'Botswana']),
  ('BR', '🇧🇷', ['Brazil', 'Brezilya', 'Brasil', 'Brasil', 'Brasilien', 'Brésil', 'Brasile', 'Бразилия', 'ブラジル', '브라질', 'Brazylia', 'บราซิล', '巴西', 'البرازيل', 'Brasil']),
  ('BN', '🇧🇳', ['Brunei', 'Bruney', 'Brunéi', 'Brunei', 'Brunei', 'Brunei', 'Brunei', 'Бруней', 'ブルネイ', '브루나이', 'Brunei', 'บรูไน', '汶萊', 'بروناي', 'Brunei']),
  ('BG', '🇧🇬', ['Bulgaria', 'Bulgaristan', 'Bulgaria', 'Bulgária', 'Bulgarien', 'Bulgarie', 'Bulgaria', 'Болгария', 'ブルガリア', '불가리아', 'Bułgaria', 'บัลแกเรีย', '保加利亞', 'بلغاريا', 'Bulgaria']),
  ('BF', '🇧🇫', ['Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burquina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Буркина-Фасо', 'ブルキナファソ', '부르키나파소', 'Burkina Faso', 'บูร์กินาฟาโซ', '布吉納法索', 'بوركينا فاسو', 'Burkina Faso']),
  ('BI', '🇧🇮', ['Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Бурунди', 'ブルンジ', '부룬디', 'Burundi', 'บุรุนดี', '蒲隆地', 'بوروندي', 'Burundi']),
  ('CV', '🇨🇻', ['Cape Verde', 'Cabo Verde', 'Cabo Verde', 'Cabo Verde', 'Kap Verde', 'Cap-Vert', 'Capo Verde', 'Кабо-Верде', 'カーボベルデ', '카보베르데', 'Republika Zielonego Przylądka', 'เคปเวิร์ด', '維德角', 'الرأس الأخضر', 'Tanjung Verde']),
  ('KH', '🇰🇭', ['Cambodia', 'Kamboçya', 'Camboya', 'Camboja', 'Kambodscha', 'Cambodge', 'Cambogia', 'Камбоджа', 'カンボジア', '캄보디아', 'Kambodża', 'กัมพูชา', '柬埔寨', 'كمبوديا', 'Kamboja']),
  ('CM', '🇨🇲', ['Cameroon', 'Kamerun', 'Camerún', 'Camarões', 'Kamerun', 'Cameroun', 'Camerun', 'Камерун', 'カメルーン', '카메룬', 'Kamerun', 'แคเมอรูน', '喀麥隆', 'الكاميرون', 'Kamerun']),
  ('CA', '🇨🇦', ['Canada', 'Kanada', 'Canadá', 'Canadá', 'Kanada', 'Canada', 'Canada', 'Канада', 'カナダ', '캐나다', 'Kanada', 'แคนาดา', '加拿大', 'كندا', 'Kanada']),
  ('CF', '🇨🇫', ['Central African Republic', 'Orta Afrika Cumhuriyeti', 'República Centroafricana', 'República Centro-Africana', 'Zentralafrikanische Republik', 'République centrafricaine', 'Repubblica Centrafricana', 'ЦАР', '中央アフリカ共和国', '중앙아프리카공화국', 'Republika Środkowoafrykańska', 'สาธารณรัฐแอฟริกากลาง', '中非共和國', 'جمهورية أفريقيا الوسطى', 'Republik Afrika Tengah']),
  ('TD', '🇹🇩', ['Chad', 'Çad', 'Chad', 'Chade', 'Tschad', 'Tchad', 'Ciad', 'Чад', 'チャド', '차드', 'Czad', 'ชาด', '查德', 'تشاد', 'Chad']),
  ('CL', '🇨🇱', ['Chile', 'Şili', 'Chile', 'Chile', 'Chile', 'Chili', 'Cile', 'Чили', 'チリ', '칠레', 'Chile', 'ชิลี', '智利', 'تشيلي', 'Chili']),
  ('CN', '🇨🇳', ['China', 'Çin', 'China', 'China', 'China', 'Chine', 'Cina', 'Китай', '中国', '중국', 'Chiny', 'จีน', '中國', 'الصين', 'Tiongkok']),
  ('CO', '🇨🇴', ['Colombia', 'Kolombiya', 'Colombia', 'Colômbia', 'Kolumbien', 'Colombie', 'Colombia', 'Колумбия', 'コロンビア', '콜롬비아', 'Kolumbia', 'โคลอมเบีย', '哥倫比亞', 'كولومبيا', 'Kolombia']),
  ('KM', '🇰🇲', ['Comoros', 'Komorlar', 'Comoras', 'Comores', 'Komoren', 'Comores', 'Comore', 'Коморы', 'コモロ', '코모로', 'Komory', 'คอโมโรส', '葛摩', 'جزر القمر', 'Komoro']),
  ('CG', '🇨🇬', ['Congo', 'Kongo', 'Congo', 'Congo', 'Kongo', 'Congo', 'Congo', 'Конго', 'コンゴ共和国', '콩고', 'Kongo', 'คองโก', '剛果', 'الكونغو', 'Kongo']),
  ('CD', '🇨🇩', ['Congo (DRC)', 'Kongo (DRC)', 'Congo (RDC)', 'Congo (RDC)', 'Kongo (DR)', 'Congo (RDC)', 'Congo (RDC)', 'ДР Конго', 'コンゴ民主共和国', '콩고민주공화국', 'DR Konga', 'คองโก (DRC)', '剛果民主共和國', 'الكونغو الديمقراطية', 'Kongo (RDK)']),
  ('CR', '🇨🇷', ['Costa Rica', 'Kosta Rika', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Коста-Рика', 'コスタリカ', '코스타리카', 'Kostaryka', 'คอสตาริกา', '哥斯大黎加', 'كوستاريكا', 'Kosta Rika']),
  ('HR', '🇭🇷', ['Croatia', 'Hırvatistan', 'Croacia', 'Croácia', 'Kroatien', 'Croatie', 'Croazia', 'Хорватия', 'クロアチア', '크로아티아', 'Chorwacja', 'โครเอเชีย', '克羅埃西亞', 'كرواتيا', 'Kroasia']),
  ('CU', '🇨🇺', ['Cuba', 'Küba', 'Cuba', 'Cuba', 'Kuba', 'Cuba', 'Cuba', 'Куба', 'キューバ', '쿠바', 'Kuba', 'คิวบา', '古巴', 'كوبا', 'Kuba']),
  ('CY', '🇨🇾', ['Cyprus', 'Kıbrıs', 'Chipre', 'Chipre', 'Zypern', 'Chypre', 'Cipro', 'Кипр', 'キプロス', '키프로스', 'Cypr', 'ไซปรัส', '賽普勒斯', 'قبرص', 'Siprus']),
  ('CZ', '🇨🇿', ['Czechia', 'Çekya', 'Chequia', 'Chéquia', 'Tschechien', 'Tchéquie', 'Cechia', 'Чехия', 'チェコ', '체코', 'Czechy', 'เช็กเกีย', '捷克', 'التشيك', 'Ceko']),
  ('DK', '🇩🇰', ['Denmark', 'Danimarka', 'Dinamarca', 'Dinamarca', 'Dänemark', 'Danemark', 'Danimarca', 'Дания', 'デンマーク', '덴마크', 'Dania', 'เดนมาร์ก', '丹麥', 'الدنمارك', 'Denmark']),
  ('DJ', '🇩🇯', ['Djibouti', 'Cibuti', 'Yibuti', 'Djibouti', 'Dschibuti', 'Djibouti', 'Gibuti', 'Джибути', 'ジブチ', '지부티', 'Dżibuti', 'จิบูตี', '吉布地', 'جيبوتي', 'Djibouti']),
  ('DO', '🇩🇴', ['Dominican Republic', 'Dominik Cumhuriyeti', 'República Dominicana', 'República Dominicana', 'Dominikanische Republik', 'République dominicaine', 'Repubblica Dominicana', 'Доминиканская Республика', 'ドミニカ共和国', '도미니카공화국', 'Dominikana', 'สาธารณรัฐโดมินิกัน', '多明尼加', 'جمهورية الدومينيكان', 'Republik Dominika']),
  ('EC', '🇪🇨', ['Ecuador', 'Ekvador', 'Ecuador', 'Equador', 'Ecuador', 'Équateur', 'Ecuador', 'Эквадор', 'エクアドル', '에콰도르', 'Ekwador', 'เอกวาดอร์', '厄瓜多', 'الإكوادور', 'Ekuador']),
  ('EG', '🇪🇬', ['Egypt', 'Mısır', 'Egipto', 'Egito', 'Ägypten', 'Égypte', 'Egitto', 'Египет', 'エジプト', '이집트', 'Egipt', 'อียิปต์', '埃及', 'مصر', 'Mesir']),
  ('SV', '🇸🇻', ['El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'Salvador', 'El Salvador', 'Сальвадор', 'エルサルバドル', '엘살바도르', 'Salwador', 'เอลซัลวาดอร์', '薩爾瓦多', 'السلفادور', 'El Salvador']),
  ('GQ', '🇬🇶', ['Equatorial Guinea', 'Ekvator Ginesi', 'Guinea Ecuatorial', 'Guiné Equatorial', 'Äquatorialguinea', 'Guinée équatoriale', 'Guinea Equatoriale', 'Экваториальная Гвинея', '赤道ギニア', '적도기니', 'Gwinea Równikowa', 'อิเควทอเรียลกินี', '赤道幾內亞', 'غينيا الاستوائية', 'Guinea Khatulistiwa']),
  ('ER', '🇪🇷', ['Eritrea', 'Eritre', 'Eritrea', 'Eritreia', 'Eritrea', 'Érythrée', 'Eritrea', 'Эритрея', 'エリトリア', '에리트레아', 'Erytrea', 'เอริเทรีย', '厄利垂亞', 'إريتريا', 'Eritrea']),
  ('EE', '🇪🇪', ['Estonia', 'Estonya', 'Estonia', 'Estônia', 'Estland', 'Estonie', 'Estonia', 'Эстония', 'エストニア', '에스토니아', 'Estonia', 'เอสโตเนีย', '愛沙尼亞', 'إستونيا', 'Estonia']),
  ('SZ', '🇸🇿', ['Eswatini', 'Esvatini', 'Esuatini', 'Essuatíni', 'Eswatini', 'Eswatini', 'Eswatini', 'Эсватини', 'エスワティニ', '에스와티니', 'Eswatini', 'เอสวาตีนี', '史瓦帝尼', 'إسواتيني', 'Eswatini']),
  ('ET', '🇪🇹', ['Ethiopia', 'Etiyopya', 'Etiopía', 'Etiópia', 'Äthiopien', 'Éthiopie', 'Etiopia', 'Эфиопия', 'エチオピア', '에티오피아', 'Etiopia', 'เอธิโอเปีย', '衣索比亞', 'إثيوبيا', 'Etiopia']),
  ('FJ', '🇫🇯', ['Fiji', 'Fiji', 'Fiyi', 'Fiji', 'Fidschi', 'Fidji', 'Figi', 'Фиджи', 'フィジー', '피지', 'Fidżi', 'ฟิจิ', '斐濟', 'فيجي', 'Fiji']),
  ('FI', '🇫🇮', ['Finland', 'Finlandiya', 'Finlandia', 'Finlândia', 'Finnland', 'Finlande', 'Finlandia', 'Финляндия', 'フィンランド', '핀란드', 'Finlandia', 'ฟินแลนด์', '芬蘭', 'فنلندا', 'Finlandia']),
  ('FR', '🇫🇷', ['France', 'Fransa', 'Francia', 'França', 'Frankreich', 'France', 'Francia', 'Франция', 'フランス', '프랑스', 'Francja', 'ฝรั่งเศส', '法國', 'فرنسا', 'Prancis']),
  ('GA', '🇬🇦', ['Gabon', 'Gabon', 'Gabón', 'Gabão', 'Gabun', 'Gabon', 'Gabon', 'Габон', 'ガボン', '가봉', 'Gabon', 'กาบอง', '加彭', 'الغابون', 'Gabon']),
  ('GM', '🇬🇲', ['Gambia', 'Gambiya', 'Gambia', 'Gâmbia', 'Gambia', 'Gambie', 'Gambia', 'Гамбия', 'ガンビア', '감비아', 'Gambia', 'แกมเบีย', '甘比亞', 'غامبيا', 'Gambia']),
  ('GE', '🇬🇪', ['Georgia', 'Gürcistan', 'Georgia', 'Geórgia', 'Georgien', 'Géorgie', 'Georgia', 'Грузия', 'ジョージア', '조지아', 'Gruzja', 'จอร์เจีย', '喬治亞', 'جورجيا', 'Georgia']),
  ('DE', '🇩🇪', ['Germany', 'Almanya', 'Alemania', 'Alemanha', 'Deutschland', 'Allemagne', 'Germania', 'Германия', 'ドイツ', '독일', 'Niemcy', 'เยอรมนี', '德國', 'ألمانيا', 'Jerman']),
  ('GH', '🇬🇭', ['Ghana', 'Gana', 'Ghana', 'Gana', 'Ghana', 'Ghana', 'Ghana', 'Гана', 'ガーナ', '가나', 'Ghana', 'กานา', '迦納', 'غانا', 'Ghana']),
  ('GR', '🇬🇷', ['Greece', 'Yunanistan', 'Grecia', 'Grécia', 'Griechenland', 'Grèce', 'Grecia', 'Греция', 'ギリシャ', '그리스', 'Grecja', 'กรีซ', '希臘', 'اليونان', 'Yunani']),
  ('GD', '🇬🇩', ['Grenada', 'Grenada', 'Granada', 'Granada', 'Grenada', 'Grenade', 'Grenada', 'Гренада', 'グレナダ', '그레나다', 'Grenada', 'เกรเนดา', '格瑞那達', 'غرينادا', 'Grenada']),
  ('GT', '🇬🇹', ['Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Гватемала', 'グアテマラ', '과테말라', 'Gwatemala', 'กัวเตมาลา', '瓜地馬拉', 'غواتيمالا', 'Guatemala']),
  ('GN', '🇬🇳', ['Guinea', 'Gine', 'Guinea', 'Guiné', 'Guinea', 'Guinée', 'Guinea', 'Гвинея', 'ギニア', '기니', 'Gwinea', 'กินี', '幾內亞', 'غينيا', 'Guinea']),
  ('GW', '🇬🇼', ['Guinea-Bissau', 'Gine-Bissau', 'Guinea-Bisáu', 'Guiné-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bissau', 'Гвинея-Бисау', 'ギニアビサウ', '기니비사우', 'Gwinea Bissau', 'กินี-บิสเซา', '幾內亞比索', 'غينيا بيساو', 'Guinea-Bissau']),
  ('GY', '🇬🇾', ['Guyana', 'Guyana', 'Guyana', 'Guiana', 'Guyana', 'Guyana', 'Guyana', 'Гайана', 'ガイアナ', '가이아나', 'Gujana', 'กายอานา', '蓋亞那', 'غيانا', 'Guyana']),
  ('HT', '🇭🇹', ['Haiti', 'Haiti', 'Haití', 'Haiti', 'Haiti', 'Haïti', 'Haiti', 'Гаити', 'ハイチ', '아이티', 'Haiti', 'เฮติ', '海地', 'هايتي', 'Haiti']),
  ('HN', '🇭🇳', ['Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Гондурас', 'ホンジュラス', '온두라스', 'Honduras', 'ฮอนดูรัส', '宏都拉斯', 'هندوراس', 'Honduras']),
  ('HU', '🇭🇺', ['Hungary', 'Macaristan', 'Hungría', 'Hungria', 'Ungarn', 'Hongrie', 'Ungheria', 'Венгрия', 'ハンガリー', '헝가리', 'Węgry', 'ฮังการี', '匈牙利', 'المجر', 'Hongaria']),
  ('IS', '🇮🇸', ['Iceland', 'İzlanda', 'Islandia', 'Islândia', 'Island', 'Islande', 'Islanda', 'Исландия', 'アイスランド', '아이슬란드', 'Islandia', 'ไอซ์แลนด์', '冰島', 'آيسلندا', 'Islandia']),
  ('IN', '🇮🇳', ['India', 'Hindistan', 'India', 'Índia', 'Indien', 'Inde', 'India', 'Индия', 'インド', '인도', 'Indie', 'อินเดีย', '印度', 'الهند', 'India']),
  ('ID', '🇮🇩', ['Indonesia', 'Endonezya', 'Indonesia', 'Indonésia', 'Indonesien', 'Indonésie', 'Indonesia', 'Индонезия', 'インドネシア', '인도네시아', 'Indonezja', 'อินโดนีเซีย', '印尼', 'إندونيسيا', 'Indonesia']),
  ('IR', '🇮🇷', ['Iran', 'İran', 'Irán', 'Irã', 'Iran', 'Iran', 'Iran', 'Иран', 'イラン', '이란', 'Iran', 'อิหร่าน', '伊朗', 'إيران', 'Iran']),
  ('IQ', '🇮🇶', ['Iraq', 'Irak', 'Irak', 'Iraque', 'Irak', 'Irak', 'Iraq', 'Ирак', 'イラク', '이라크', 'Irak', 'อิรัก', '伊拉克', 'العراق', 'Irak']),
  ('IE', '🇮🇪', ['Ireland', 'İrlanda', 'Irlanda', 'Irlanda', 'Irland', 'Irlande', 'Irlanda', 'Ирландия', 'アイルランド', '아일랜드', 'Irlandia', 'ไอร์แลนด์', '愛爾蘭', 'أيرلندا', 'Irlandia']),
  ('IL', '🇮🇱', ['Israel', 'İsrail', 'Israel', 'Israel', 'Israel', 'Israël', 'Israele', 'Израиль', 'イスラエル', '이스라엘', 'Izrael', 'อิสราเอล', '以色列', 'إسرائيل', 'Israel']),
  ('IT', '🇮🇹', ['Italy', 'İtalya', 'Italia', 'Itália', 'Italien', 'Italie', 'Italia', 'Италия', 'イタリア', '이탈리아', 'Włochy', 'อิตาลี', '義大利', 'إيطاليا', 'Italia']),
  ('JM', '🇯🇲', ['Jamaica', 'Jamaika', 'Jamaica', 'Jamaica', 'Jamaika', 'Jamaïque', 'Giamaica', 'Ямайка', 'ジャマイカ', '자메이카', 'Jamajka', 'จาเมกา', '牙買加', 'جامايكا', 'Jamaika']),
  ('JP', '🇯🇵', ['Japan', 'Japonya', 'Japón', 'Japão', 'Japan', 'Japon', 'Giappone', 'Япония', '日本', '일본', 'Japonia', 'ญี่ปุ่น', '日本', 'اليابان', 'Jepang']),
  ('JO', '🇯🇴', ['Jordan', 'Ürdün', 'Jordania', 'Jordânia', 'Jordanien', 'Jordanie', 'Giordania', 'Иордания', 'ヨルダン', '요르단', 'Jordania', 'จอร์แดน', '約旦', 'الأردن', 'Yordania']),
  ('KZ', '🇰🇿', ['Kazakhstan', 'Kazakistan', 'Kazajistán', 'Cazaquistão', 'Kasachstan', 'Kazakhstan', 'Kazakistan', 'Казахстан', 'カザフスタン', '카자흐스탄', 'Kazachstan', 'คาซัคสถาน', '哈薩克', 'كازاخستان', 'Kazakhstan']),
  ('KE', '🇰🇪', ['Kenya', 'Kenya', 'Kenia', 'Quênia', 'Kenia', 'Kenya', 'Kenya', 'Кения', 'ケニア', '케냐', 'Kenia', 'เคนยา', '肯亞', 'كينيا', 'Kenya']),
  ('KI', '🇰🇮', ['Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Кирибати', 'キリバス', '키리바시', 'Kiribati', 'คิริบาส', '吉里巴斯', 'كيريباتي', 'Kiribati']),
  ('XK', '🇽🇰', ['Kosovo', 'Kosova', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Косово', 'コソボ', '코소보', 'Kosowo', 'โคโซโว', '科索沃', 'كوسوفو', 'Kosovo']),
  ('KW', '🇰🇼', ['Kuwait', 'Kuveyt', 'Kuwait', 'Kuwait', 'Kuwait', 'Koweït', 'Kuwait', 'Кувейт', 'クウェート', '쿠웨이트', 'Kuwejt', 'คูเวต', '科威特', 'الكويت', 'Kuwait']),
  ('KG', '🇰🇬', ['Kyrgyzstan', 'Kırgızistan', 'Kirguistán', 'Quirguistão', 'Kirgisistan', 'Kirghizistan', 'Kirghizistan', 'Киргизия', 'キルギス', '키르기스스탄', 'Kirgistan', 'คีร์กีซสถาน', '吉爾吉斯', 'قيرغيزستان', 'Kirgistan']),
  ('LA', '🇱🇦', ['Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Лаос', 'ラオス', '라오스', 'Laos', 'ลาว', '寮國', 'لاوس', 'Laos']),
  ('LV', '🇱🇻', ['Latvia', 'Letonya', 'Letonia', 'Letônia', 'Lettland', 'Lettonie', 'Lettonia', 'Латвия', 'ラトビア', '라트비아', 'Łotwa', 'ลัตเวีย', '拉脫維亞', 'لاتفيا', 'Latvia']),
  ('LB', '🇱🇧', ['Lebanon', 'Lübnan', 'Líbano', 'Líbano', 'Libanon', 'Liban', 'Libano', 'Ливан', 'レバノン', '레바논', 'Liban', 'เลบานอน', '黎巴嫩', 'لبنان', 'Lebanon']),
  ('LS', '🇱🇸', ['Lesotho', 'Lesotho', 'Lesoto', 'Lesoto', 'Lesotho', 'Lesotho', 'Lesotho', 'Лесото', 'レソト', '레소토', 'Lesotho', 'เลโซโท', '賴索托', 'ليسوتو', 'Lesotho']),
  ('LR', '🇱🇷', ['Liberia', 'Liberya', 'Liberia', 'Libéria', 'Liberia', 'Liberia', 'Liberia', 'Либерия', 'リベリア', '라이베리아', 'Liberia', 'ไลบีเรีย', '賴比瑞亞', 'ليبيريا', 'Liberia']),
  ('LY', '🇱🇾', ['Libya', 'Libya', 'Libia', 'Líbia', 'Libyen', 'Libye', 'Libia', 'Ливия', 'リビア', '리비아', 'Libia', 'ลิเบีย', '利比亞', 'ليبيا', 'Libya']),
  ('LI', '🇱🇮', ['Liechtenstein', 'Lihtenştayn', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Лихтенштейн', 'リヒテンシュタイン', '리히텐슈타인', 'Liechtenstein', 'ลิกเตนสไตน์', '列支敦斯登', 'ليختنشتاين', 'Liechtenstein']),
  ('LT', '🇱🇹', ['Lithuania', 'Litvanya', 'Lituania', 'Lituânia', 'Litauen', 'Lituanie', 'Lituania', 'Литва', 'リトアニア', '리투아니아', 'Litwa', 'ลิทัวเนีย', '立陶宛', 'ليتوانيا', 'Lituania']),
  ('LU', '🇱🇺', ['Luxembourg', 'Lüksemburg', 'Luxemburgo', 'Luxemburgo', 'Luxemburg', 'Luxembourg', 'Lussemburgo', 'Люксембург', 'ルクセンブルク', '룩셈부르크', 'Luksemburg', 'ลักเซมเบิร์ก', '盧森堡', 'لوكسمبورغ', 'Luksemburg']),
  ('MG', '🇲🇬', ['Madagascar', 'Madagaskar', 'Madagascar', 'Madagáscar', 'Madagaskar', 'Madagascar', 'Madagascar', 'Мадагаскар', 'マダガスカル', '마다가스카르', 'Madagaskar', 'มาดากัสการ์', '馬達加斯加', 'مدغشقر', 'Madagaskar']),
  ('MW', '🇲🇼', ['Malawi', 'Malavi', 'Malaui', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Малави', 'マラウイ', '말라위', 'Malawi', 'มาลาวี', '馬拉威', 'مالاوي', 'Malawi']),
  ('MY', '🇲🇾', ['Malaysia', 'Malezya', 'Malasia', 'Malásia', 'Malaysia', 'Malaisie', 'Malaysia', 'Малайзия', 'マレーシア', '말레이시아', 'Malezja', 'มาเลเซีย', '馬來西亞', 'ماليزيا', 'Malaysia']),
  ('MV', '🇲🇻', ['Maldives', 'Maldivler', 'Maldivas', 'Maldivas', 'Malediven', 'Maldives', 'Maldive', 'Мальдивы', 'モルディブ', '몰디브', 'Malediwy', 'มัลดีฟส์', '馬爾地夫', 'جزر المالديف', 'Maladewa']),
  ('ML', '🇲🇱', ['Mali', 'Mali', 'Malí', 'Mali', 'Mali', 'Mali', 'Mali', 'Мали', 'マリ', '말리', 'Mali', 'มาลี', '馬利', 'مالي', 'Mali']),
  ('MT', '🇲🇹', ['Malta', 'Malta', 'Malta', 'Malta', 'Malta', 'Malte', 'Malta', 'Мальта', 'マルタ', '몰타', 'Malta', 'มอลตา', '馬爾他', 'مالطا', 'Malta']),
  ('MH', '🇲🇭', ['Marshall Islands', 'Marşal Adaları', 'Islas Marshall', 'Ilhas Marshall', 'Marshallinseln', 'Îles Marshall', 'Isole Marshall', 'Маршалловы Острова', 'マーシャル諸島', '마셜 제도', 'Wyspy Marshalla', 'หมู่เกาะมาร์แชลล์', '馬紹爾群島', 'جزر مارشال', 'Kepulauan Marshall']),
  ('MR', '🇲🇷', ['Mauritania', 'Moritanya', 'Mauritania', 'Mauritânia', 'Mauretanien', 'Mauritanie', 'Mauritania', 'Мавритания', 'モーリタニア', '모리타니', 'Mauretania', 'มอริเตเนีย', '茅利塔尼亞', 'موريتانيا', 'Mauritania']),
  ('MU', '🇲🇺', ['Mauritius', 'Mauritius', 'Mauricio', 'Maurícia', 'Mauritius', 'Maurice', 'Mauritius', 'Маврикий', 'モーリシャス', '모리셔스', 'Mauritius', 'มอริเชียส', '模里西斯', 'موريشيوس', 'Mauritius']),
  ('MX', '🇲🇽', ['Mexico', 'Meksika', 'México', 'México', 'Mexiko', 'Mexique', 'Messico', 'Мексика', 'メキシコ', '멕시코', 'Meksyk', 'เม็กซิโก', '墨西哥', 'المكسيك', 'Meksiko']),
  ('FM', '🇫🇲', ['Micronesia', 'Mikronezya', 'Micronesia', 'Micronésia', 'Mikronesien', 'Micronésie', 'Micronesia', 'Микронезия', 'ミクロネシア', '미크로네시아', 'Mikronezja', 'ไมโครนีเซีย', '密克羅尼西亞', 'ميكرونيزيا', 'Mikronesia']),
  ('MD', '🇲🇩', ['Moldova', 'Moldova', 'Moldavia', 'Moldávia', 'Moldau', 'Moldavie', 'Moldavia', 'Молдова', 'モルドバ', '몰도바', 'Mołdawia', 'มอลโดวา', '摩爾多瓦', 'مولدوفا', 'Moldova']),
  ('MC', '🇲🇨', ['Monaco', 'Monako', 'Mónaco', 'Mônaco', 'Monaco', 'Monaco', 'Monaco', 'Монако', 'モナコ', '모나코', 'Monako', 'โมนาโก', '摩納哥', 'موناكو', 'Monako']),
  ('MN', '🇲🇳', ['Mongolia', 'Moğolistan', 'Mongolia', 'Mongólia', 'Mongolei', 'Mongolie', 'Mongolia', 'Монголия', 'モンゴル', '몽골', 'Mongolia', 'มองโกเลีย', '蒙古', 'منغوليا', 'Mongolia']),
  ('ME', '🇲🇪', ['Montenegro', 'Karadağ', 'Montenegro', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro', 'Черногория', 'モンテネグロ', '몬테네그로', 'Czarnogóra', 'มอนเตเนโกร', '蒙特內哥羅', 'الجبل الأسود', 'Montenegro']),
  ('MA', '🇲🇦', ['Morocco', 'Fas', 'Marruecos', 'Marrocos', 'Marokko', 'Maroc', 'Marocco', 'Марокко', 'モロッコ', '모로코', 'Maroko', 'โมร็อกโก', '摩洛哥', 'المغرب', 'Maroko']),
  ('MZ', '🇲🇿', ['Mozambique', 'Mozambik', 'Mozambique', 'Moçambique', 'Mosambik', 'Mozambique', 'Mozambico', 'Мозамбик', 'モザンビーク', '모잠비크', 'Mozambik', 'โมซัมบิก', '莫三比克', 'موزمبيق', 'Mozambik']),
  ('MM', '🇲🇲', ['Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'Мьянма', 'ミャンマー', '미얀마', 'Mjanma', 'เมียนมา', '緬甸', 'ميانمار', 'Myanmar']),
  ('NA', '🇳🇦', ['Namibia', 'Namibya', 'Namibia', 'Namíbia', 'Namibia', 'Namibie', 'Namibia', 'Намибия', 'ナミビア', '나미비아', 'Namibia', 'นามิเบีย', '納米比亞', 'ناميبيا', 'Namibia']),
  ('NR', '🇳🇷', ['Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Науру', 'ナウル', '나우루', 'Nauru', 'นาอูรู', '諾魯', 'ناورو', 'Nauru']),
  ('NP', '🇳🇵', ['Nepal', 'Nepal', 'Nepal', 'Nepal', 'Nepal', 'Népal', 'Nepal', 'Непал', 'ネパール', '네팔', 'Nepal', 'เนปาล', '尼泊爾', 'نيبال', 'Nepal']),
  ('NL', '🇳🇱', ['Netherlands', 'Hollanda', 'Países Bajos', 'Países Baixos', 'Niederlande', 'Pays-Bas', 'Paesi Bassi', 'Нидерланды', 'オランダ', '네덜란드', 'Holandia', 'เนเธอร์แลนด์', '荷蘭', 'هولندا', 'Belanda']),
  ('NZ', '🇳🇿', ['New Zealand', 'Yeni Zelanda', 'Nueva Zelanda', 'Nova Zelândia', 'Neuseeland', 'Nouvelle-Zélande', 'Nuova Zelanda', 'Новая Зеландия', 'ニュージーランド', '뉴질랜드', 'Nowa Zelandia', 'นิวซีแลนด์', '紐西蘭', 'نيوزيلندا', 'Selandia Baru']),
  ('NI', '🇳🇮', ['Nicaragua', 'Nikaragua', 'Nicaragua', 'Nicarágua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Никарагуа', 'ニカラグア', '니카라과', 'Nikaragua', 'นิการากัว', '尼加拉瓜', 'نيكاراغوا', 'Nikaragua']),
  ('NE', '🇳🇪', ['Niger', 'Nijer', 'Níger', 'Níger', 'Niger', 'Niger', 'Niger', 'Нигер', 'ニジェール', '니제르', 'Niger', 'ไนเจอร์', '尼日', 'النيجر', 'Niger']),
  ('NG', '🇳🇬', ['Nigeria', 'Nijerya', 'Nigeria', 'Nigéria', 'Nigeria', 'Nigeria', 'Nigeria', 'Нигерия', 'ナイジェリア', '나이지리아', 'Nigeria', 'ไนจีเรีย', '奈及利亞', 'نيجيريا', 'Nigeria']),
  ('KP', '🇰🇵', ['North Korea', 'Kuzey Kore', 'Corea del Norte', 'Coreia do Norte', 'Nordkorea', 'Corée du Nord', 'Corea del Nord', 'Северная Корея', '北朝鮮', '조선민주주의인민공화국', 'Korea Północna', 'เกาหลีเหนือ', '北韓', 'كوريا الشمالية', 'Korea Utara']),
  ('MK', '🇲🇰', ['North Macedonia', 'Kuzey Makedonya', 'Macedonia del Norte', 'Macedônia do Norte', 'Nordmazedonien', 'Macédoine du Nord', 'Macedonia del Nord', 'Северная Македония', '北マケドニア', '북마케도니아', 'Macedonia Północna', 'มาซิโดเนียเหนือ', '北馬其頓', 'مقدونيا الشمالية', 'Makedonia Utara']),
  ('NO', '🇳🇴', ['Norway', 'Norveç', 'Noruega', 'Noruega', 'Norwegen', 'Norvège', 'Norvegia', 'Норвегия', 'ノルウェー', '노르웨이', 'Norwegia', 'นอร์เวย์', '挪威', 'النرويج', 'Norwegia']),
  ('OM', '🇴🇲', ['Oman', 'Umman', 'Omán', 'Omã', 'Oman', 'Oman', 'Oman', 'Оман', 'オマーン', '오만', 'Oman', 'โอมาน', '阿曼', 'عُمان', 'Oman']),
  ('PK', '🇵🇰', ['Pakistan', 'Pakistan', 'Pakistán', 'Paquistão', 'Pakistan', 'Pakistan', 'Pakistan', 'Пакистан', 'パキスタン', '파키스탄', 'Pakistan', 'ปากีสถาน', '巴基斯坦', 'باكستان', 'Pakistan']),
  ('PW', '🇵🇼', ['Palau', 'Palau', 'Palaos', 'Palau', 'Palau', 'Palaos', 'Palau', 'Палау', 'パラオ', '팔라우', 'Palau', 'ปาเลา', '帛琉', 'بالاو', 'Palau']),
  ('PS', '🇵🇸', ['Palestine', 'Filistin', 'Palestina', 'Palestina', 'Palästina', 'Palestine', 'Palestina', 'Палестина', 'パレスチナ', '팔레스타인', 'Palestyna', 'ปาเลสไตน์', '巴勒斯坦', 'فلسطين', 'Palestina']),
  ('PA', '🇵🇦', ['Panama', 'Panama', 'Panamá', 'Panamá', 'Panama', 'Panama', 'Panama', 'Панама', 'パナマ', '파나마', 'Panama', 'ปานามา', '巴拿馬', 'بنما', 'Panama']),
  ('PG', '🇵🇬', ['Papua New Guinea', 'Papua Yeni Gine', 'Papúa Nueva Guinea', 'Papua-Nova Guiné', 'Papua-Neuguinea', 'Papouasie-Nouvelle-Guinée', 'Papua Nuova Guinea', 'Папуа — Новая Гвинея', 'パプアニューギニア', '파푸아뉴기니', 'Papua-Nowa Gwinea', 'ปาปัวนิวกินี', '巴布亞紐幾內亞', 'بابوا غينيا الجديدة', 'Papua Nugini']),
  ('PY', '🇵🇾', ['Paraguay', 'Paraguay', 'Paraguay', 'Paraguai', 'Paraguay', 'Paraguay', 'Paraguay', 'Парагвай', 'パラグアイ', '파라과이', 'Paragwaj', 'ปารากวัย', '巴拉圭', 'باراغواي', 'Paraguay']),
  ('PE', '🇵🇪', ['Peru', 'Peru', 'Perú', 'Peru', 'Peru', 'Pérou', 'Perù', 'Перу', 'ペルー', '페루', 'Peru', 'เปรู', '秘魯', 'بيرو', 'Peru']),
  ('PH', '🇵🇭', ['Philippines', 'Filipinler', 'Filipinas', 'Filipinas', 'Philippinen', 'Philippines', 'Filippine', 'Филиппины', 'フィリピン', '필리핀', 'Filipiny', 'ฟิลิปปินส์', '菲律賓', 'الفلبين', 'Filipina']),
  ('PL', '🇵🇱', ['Poland', 'Polonya', 'Polonia', 'Polônia', 'Polen', 'Pologne', 'Polonia', 'Польша', 'ポーランド', '폴란드', 'Polska', 'โปแลนด์', '波蘭', 'بولندا', 'Polandia']),
  ('PT', '🇵🇹', ['Portugal', 'Portekiz', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portogallo', 'Португалия', 'ポルトガル', '포르투갈', 'Portugalia', 'โปรตุเกส', '葡萄牙', 'البرتغال', 'Portugal']),
  ('QA', '🇶🇦', ['Qatar', 'Katar', 'Catar', 'Catar', 'Katar', 'Qatar', 'Qatar', 'Катар', 'カタール', '카타르', 'Katar', 'กาตาร์', '卡達', 'قطر', 'Qatar']),
  ('RO', '🇷🇴', ['Romania', 'Romanya', 'Rumanía', 'Romênia', 'Rumänien', 'Roumanie', 'Romania', 'Румыния', 'ルーマニア', '루마니아', 'Rumunia', 'โรมาเนีย', '羅馬尼亞', 'رومانيا', 'Rumania']),
  ('RU', '🇷🇺', ['Russia', 'Rusya', 'Rusia', 'Rússia', 'Russland', 'Russie', 'Russia', 'Россия', 'ロシア', '러시아', 'Rosja', 'รัสเซีย', '俄羅斯', 'روسيا', 'Rusia']),
  ('RW', '🇷🇼', ['Rwanda', 'Ruanda', 'Ruanda', 'Ruanda', 'Ruanda', 'Rwanda', 'Ruanda', 'Руанда', 'ルワンダ', '르완다', 'Rwanda', 'รวันดา', '盧安達', 'رواندا', 'Rwanda']),
  ('KN', '🇰🇳', ['St Kitts & Nevis', 'Saint Kitts ve Nevis', 'San Cristóbal y Nieves', 'São Cristóvão e Neves', 'St. Kitts und Nevis', 'Saint-Christophe-et-Niévès', 'Saint Kitts e Nevis', 'Сент-Китс и Невис', 'セントクリストファー・ネイビス', '세인트키츠 네비스', 'Saint Kitts i Nevis', 'เซนต์คิตส์และเนวิส', '聖克里斯多福及尼維斯', 'سانت كيتس ونيفيس', 'Saint Kitts dan Nevis']),
  ('LC', '🇱🇨', ['Saint Lucia', 'Saint Lucia', 'Santa Lucía', 'Santa Lúcia', 'St. Lucia', 'Sainte-Lucie', 'Saint Lucia', 'Сент-Люсия', 'セントルシア', '세인트루시아', 'Saint Lucia', 'เซนต์ลูเซีย', '聖露西亞', 'سانت لوسيا', 'Saint Lucia']),
  ('VC', '🇻🇨', ['St Vincent & Grenadines', 'Saint Vincent ve Grenadinler', 'San Vicente y las Granadinas', 'São Vicente e Granadinas', 'St. Vincent und die Grenadinen', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent e Grenadine', 'Сент-Винсент и Гренадины', 'セントビンセントおよびグレナディーン諸島', '세인트빈센트 그레나딘', 'Saint Vincent i Grenadyny', 'เซนต์วินเซนต์', '聖文森', 'سانت فينسنت', 'Saint Vincent dan Grenadine']),
  ('WS', '🇼🇸', ['Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Самоа', 'サモア', '사모아', 'Samoa', 'ซามัว', '薩摩亞', 'ساموا', 'Samoa']),
  ('SM', '🇸🇲', ['San Marino', 'San Marino', 'San Marino', 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino', 'Сан-Марино', 'サンマリノ', '산마리노', 'San Marino', 'ซานมารีโน', '聖馬利諾', 'سان مارينو', 'San Marino']),
  ('ST', '🇸🇹', ['São Tomé & Príncipe', 'São Tomé ve Príncipe', 'Santo Tomé y Príncipe', 'São Tomé e Príncipe', 'São Tomé und Príncipe', 'Sao Tomé-et-Principe', 'São Tomé e Príncipe', 'Сан-Томе и Принсипи', 'サントメ・プリンシペ', '상투메 프린시페', 'Wyspy Świętego Tomasza i Książęca', 'เซาตูเมและปรินซิปี', '聖多美普林西比', 'ساو تومي وبرينسيبي', 'Sao Tome dan Principe']),
  ('SA', '🇸🇦', ['Saudi Arabia', 'Suudi Arabistan', 'Arabia Saudita', 'Arábia Saudita', 'Saudi-Arabien', 'Arabie saoudite', 'Arabia Saudita', 'Саудовская Аравия', 'サウジアラビア', '사우디아라비아', 'Arabia Saudyjska', 'ซาอุดีอาระเบีย', '沙烏地阿拉伯', 'السعودية', 'Arab Saudi']),
  ('SN', '🇸🇳', ['Senegal', 'Senegal', 'Senegal', 'Senegal', 'Senegal', 'Sénégal', 'Senegal', 'Сенегал', 'セネガル', '세네갈', 'Senegal', 'เซเนกัล', '塞內加爾', 'السنغال', 'Senegal']),
  ('RS', '🇷🇸', ['Serbia', 'Sırbistan', 'Serbia', 'Sérvia', 'Serbien', 'Serbie', 'Serbia', 'Сербия', 'セルビア', '세르비아', 'Serbia', 'เซอร์เบีย', '塞爾維亞', 'صربيا', 'Serbia']),
  ('SC', '🇸🇨', ['Seychelles', 'Seyşeller', 'Seychelles', 'Seicheles', 'Seychellen', 'Seychelles', 'Seychelles', 'Сейшелы', 'セーシェル', '세이셸', 'Seszele', 'เซเชลส์', '塞席爾', 'سيشل', 'Seychelles']),
  ('SL', '🇸🇱', ['Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'Serra Leoa', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Сьерра-Леоне', 'シエラレオネ', '시에라리온', 'Sierra Leone', 'เซียร์ราลีโอน', '獅子山', 'سيراليون', 'Sierra Leone']),
  ('SG', '🇸🇬', ['Singapore', 'Singapur', 'Singapur', 'Singapura', 'Singapur', 'Singapour', 'Singapore', 'Сингапур', 'シンガポール', '싱가포르', 'Singapur', 'สิงคโปร์', '新加坡', 'سنغافورة', 'Singapura']),
  ('SK', '🇸🇰', ['Slovakia', 'Slovakya', 'Eslovaquia', 'Eslováquia', 'Slowakei', 'Slovaquie', 'Slovacchia', 'Словакия', 'スロバキア', '슬로바키아', 'Słowacja', 'สโลวาเกีย', '斯洛伐克', 'سلوفاكيا', 'Slowakia']),
  ('SI', '🇸🇮', ['Slovenia', 'Slovenya', 'Eslovenia', 'Eslovênia', 'Slowenien', 'Slovénie', 'Slovenia', 'Словения', 'スロベニア', '슬로베니아', 'Słowenia', 'สโลวีเนีย', '斯洛維尼亞', 'سلوفينيا', 'Slovenia']),
  ('SB', '🇸🇧', ['Solomon Islands', 'Solomon Adaları', 'Islas Salomón', 'Ilhas Salomão', 'Salomonen', 'Îles Salomon', 'Isole Salomone', 'Соломоновы Острова', 'ソロモン諸島', '솔로몬 제도', 'Wyspy Salomona', 'หมู่เกาะโซโลมอน', '索羅門群島', 'جزر سليمان', 'Kepulauan Solomon']),
  ('SO', '🇸🇴', ['Somalia', 'Somali', 'Somalia', 'Somália', 'Somalia', 'Somalie', 'Somalia', 'Сомали', 'ソマリア', '소말리아', 'Somalia', 'โซมาเลีย', '索馬利亞', 'الصومال', 'Somalia']),
  ('ZA', '🇿🇦', ['South Africa', 'Güney Afrika', 'Sudáfrica', 'África do Sul', 'Südafrika', 'Afrique du Sud', 'Sudafrica', 'ЮАР', '南アフリカ', '남아프리카공화국', 'RPA', 'แอฟริกาใต้', '南非', 'جنوب أفريقيا', 'Afrika Selatan']),
  ('SS', '🇸🇸', ['South Sudan', 'Güney Sudan', 'Sudán del Sur', 'Sudão do Sul', 'Südsudan', 'Soudan du Sud', 'Sudan del Sud', 'Южный Судан', '南スーダン', '남수단', 'Sudan Południowy', 'ซูดานใต้', '南蘇丹', 'جنوب السودان', 'Sudan Selatan']),
  ('KR', '🇰🇷', ['South Korea', 'Güney Kore', 'Corea del Sur', 'Coreia do Sul', 'Südkorea', 'Corée du Sud', 'Corea del Sud', 'Южная Корея', '韓国', '대한민국', 'Korea Południowa', 'เกาหลีใต้', '南韓', 'كوريا الجنوبية', 'Korea Selatan']),
  ('ES', '🇪🇸', ['Spain', 'İspanya', 'España', 'Espanha', 'Spanien', 'Espagne', 'Spagna', 'Испания', 'スペイン', '스페인', 'Hiszpania', 'สเปน', '西班牙', 'إسبانيا', 'Spanyol']),
  ('LK', '🇱🇰', ['Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Шри-Ланка', 'スリランカ', '스리랑카', 'Sri Lanka', 'ศรีลังกา', '斯里蘭卡', 'سريلانكا', 'Sri Lanka']),
  ('SD', '🇸🇩', ['Sudan', 'Sudan', 'Sudán', 'Sudão', 'Sudan', 'Soudan', 'Sudan', 'Судан', 'スーダン', '수단', 'Sudan', 'ซูดาน', '蘇丹', 'السودان', 'Sudan']),
  ('SR', '🇸🇷', ['Suriname', 'Surinam', 'Surinam', 'Suriname', 'Suriname', 'Suriname', 'Suriname', 'Суринам', 'スリナム', '수리남', 'Surinam', 'ซูรินาเม', '蘇利南', 'سورينام', 'Suriname']),
  ('SE', '🇸🇪', ['Sweden', 'İsveç', 'Suecia', 'Suécia', 'Schweden', 'Suède', 'Svezia', 'Швеция', 'スウェーデン', '스웨덴', 'Szwecja', 'สวีเดน', '瑞典', 'السويد', 'Swedia']),
  ('CH', '🇨🇭', ['Switzerland', 'İsviçre', 'Suiza', 'Suíça', 'Schweiz', 'Suisse', 'Svizzera', 'Швейцария', 'スイス', '스위스', 'Szwajcaria', 'สวิตเซอร์แลนด์', '瑞士', 'سويسرا', 'Swiss']),
  ('SY', '🇸🇾', ['Syria', 'Suriye', 'Siria', 'Síria', 'Syrien', 'Syrie', 'Siria', 'Сирия', 'シリア', '시리아', 'Syria', 'ซีเรีย', '敘利亞', 'سوريا', 'Suriah']),
  ('TW', '🇹🇼', ['Taiwan', 'Tayvan', 'Taiwán', 'Taiwan', 'Taiwan', 'Taïwan', 'Taiwan', 'Тайвань', '台湾', '대만', 'Tajwan', 'ไต้หวัน', '臺灣', 'تايوان', 'Taiwan']),
  ('TJ', '🇹🇯', ['Tajikistan', 'Tacikistan', 'Tayikistán', 'Tajiquistão', 'Tadschikistan', 'Tadjikistan', 'Tagikistan', 'Таджикистан', 'タジキスタン', '타지키스탄', 'Tadżykistan', 'ทาจิกิสถาน', '塔吉克', 'طاجيكستان', 'Tajikistan']),
  ('TZ', '🇹🇿', ['Tanzania', 'Tanzanya', 'Tanzania', 'Tanzânia', 'Tansania', 'Tanzanie', 'Tanzania', 'Танзания', 'タンザニア', '탄자니아', 'Tanzania', 'แทนซาเนีย', '坦尚尼亞', 'تنزانيا', 'Tanzania']),
  ('TH', '🇹🇭', ['Thailand', 'Tayland', 'Tailandia', 'Tailândia', 'Thailand', 'Thaïlande', 'Thailandia', 'Таиланд', 'タイ', '태국', 'Tajlandia', 'ไทย', '泰國', 'تايلاند', 'Thailand']),
  ('TL', '🇹🇱', ['Timor-Leste', 'Doğu Timor', 'Timor Oriental', 'Timor-Leste', 'Osttimor', 'Timor oriental', 'Timor Est', 'Восточный Тимор', '東ティモール', '동티모르', 'Timor Wschodni', 'ติมอร์-เลสเต', '東帝汶', 'تيمور الشرقية', 'Timor Leste']),
  ('TG', '🇹🇬', ['Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Того', 'トーゴ', '토고', 'Togo', 'โตโก', '多哥', 'توغو', 'Togo']),
  ('TO', '🇹🇴', ['Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Тонга', 'トンガ', '통가', 'Tonga', 'ตองงา', '東加', 'تونغا', 'Tonga']),
  ('TT', '🇹🇹', ['Trinidad & Tobago', 'Trinidad ve Tobago', 'Trinidad y Tobago', 'Trindade e Tobago', 'Trinidad und Tobago', 'Trinité-et-Tobago', 'Trinidad e Tobago', 'Тринидад и Тобаго', 'トリニダード・トバゴ', '트리니다드 토바고', 'Trynidad i Tobago', 'ตรินิแดดและโตเบโก', '千里達及托巴哥', 'ترينيداد وتوباغو', 'Trinidad dan Tobago']),
  ('TN', '🇹🇳', ['Tunisia', 'Tunus', 'Túnez', 'Tunísia', 'Tunesien', 'Tunisie', 'Tunisia', 'Тунис', 'チュニジア', '튀니지', 'Tunezja', 'ตูนิเซีย', '突尼西亞', 'تونس', 'Tunisia']),
  ('TR', '🇹🇷', ['Turkey', 'Türkiye', 'Turquía', 'Turquia', 'Türkei', 'Turquie', 'Turchia', 'Турция', 'トルコ', '튀르키예', 'Turcja', 'ตุรกี', '土耳其', 'تركيا', 'Turki']),
  ('TM', '🇹🇲', ['Turkmenistan', 'Türkmenistan', 'Turkmenistán', 'Turcomenistão', 'Turkmenistan', 'Turkménistan', 'Turkmenistan', 'Туркменистан', 'トルクメニスタン', '투르크메니스탄', 'Turkmenistan', 'เติร์กเมนิสถาน', '土庫曼', 'تركمانستان', 'Turkmenistan']),
  ('TV', '🇹🇻', ['Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Тувалу', 'ツバル', '투발루', 'Tuvalu', 'ตูวาลู', '吐瓦魯', 'توفالو', 'Tuvalu']),
  ('UG', '🇺🇬', ['Uganda', 'Uganda', 'Uganda', 'Uganda', 'Uganda', 'Ouganda', 'Uganda', 'Уганда', 'ウガンダ', '우간다', 'Uganda', 'ยูกันดา', '烏干達', 'أوغندا', 'Uganda']),
  ('UA', '🇺🇦', ['Ukraine', 'Ukrayna', 'Ucrania', 'Ucrânia', 'Ukraine', 'Ukraine', 'Ucraina', 'Украина', 'ウクライナ', '우크라이나', 'Ukraina', 'ยูเครน', '烏克蘭', 'أوكرانيا', 'Ukraina']),
  ('AE', '🇦🇪', ['United Arab Emirates', 'Birleşik Arap Emirlikleri', 'Emiratos Árabes Unidos', 'Emirados Árabes Unidos', 'Vereinigte Arabische Emirate', 'Émirats arabes unis', 'Emirati Arabi Uniti', 'ОАЭ', 'アラブ首長国連邦', '아랍에미리트', 'Zjednoczone Emiraty Arabskie', 'สหรัฐอาหรับเอมิเรตส์', '阿拉伯聯合大公國', 'الإمارات', 'Uni Emirat Arab']),
  ('GB', '🇬🇧', ['United Kingdom', 'Birleşik Krallık', 'Reino Unido', 'Reino Unido', 'Vereinigtes Königreich', 'Royaume-Uni', 'Regno Unito', 'Великобритания', 'イギリス', '영국', 'Wielka Brytania', 'สหราชอาณาจักร', '英國', 'المملكة المتحدة', 'Britania Raya']),
  ('US', '🇺🇸', ['United States', 'Amerika Birleşik Devletleri', 'Estados Unidos', 'Estados Unidos', 'Vereinigte Staaten', 'États-Unis', 'Stati Uniti', 'США', 'アメリカ合衆国', '미국', 'Stany Zjednoczone', 'สหรัฐอเมริกา', '美國', 'الولايات المتحدة', 'Amerika Serikat']),
  ('UY', '🇺🇾', ['Uruguay', 'Uruguay', 'Uruguay', 'Uruguai', 'Uruguay', 'Uruguay', 'Uruguay', 'Уругвай', 'ウルグアイ', '우루과이', 'Urugwaj', 'อุรุกวัย', '烏拉圭', 'الأوروغواي', 'Uruguay']),
  ('UZ', '🇺🇿', ['Uzbekistan', 'Özbekistan', 'Uzbekistán', 'Usbequistão', 'Usbekistan', 'Ouzbékistan', 'Uzbekistan', 'Узбекистан', 'ウズベキスタン', '우즈베키스탄', 'Uzbekistan', 'อุซเบกิสถาน', '烏茲別克', 'أوزبكستان', 'Uzbekistan']),
  ('VU', '🇻🇺', ['Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Вануату', 'バヌアツ', '바누아투', 'Vanuatu', 'วานูอาตู', '萬那杜', 'فانواتو', 'Vanuatu']),
  ('VA', '🇻🇦', ['Vatican City', 'Vatikan', 'Ciudad del Vaticano', 'Cidade do Vaticano', 'Vatikanstadt', 'Cité du Vatican', 'Città del Vaticano', 'Ватикан', 'バチカン', '바티칸', 'Watykan', 'นครวาติกัน', '梵蒂岡', 'الفاتيكان', 'Vatikan']),
  ('VE', '🇻🇪', ['Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Венесуэла', 'ベネズエラ', '베네수엘라', 'Wenezuela', 'เวเนซุเอลา', '委內瑞拉', 'فنزويلا', 'Venezuela']),
  ('VN', '🇻🇳', ['Vietnam', 'Vietnam', 'Vietnam', 'Vietnã', 'Vietnam', 'Vietnam', 'Vietnam', 'Вьетнам', 'ベトナム', '베트남', 'Wietnam', 'เวียดนาม', '越南', 'فيتنام', 'Vietnam']),
  ('YE', '🇾🇪', ['Yemen', 'Yemen', 'Yemen', 'Iêmen', 'Jemen', 'Yémen', 'Yemen', 'Йемен', 'イエメン', '예멘', 'Jemen', 'เยเมน', '葉門', 'اليمن', 'Yaman']),
  ('ZM', '🇿🇲', ['Zambia', 'Zambiya', 'Zambia', 'Zâmbia', 'Sambia', 'Zambie', 'Zambia', 'Замбия', 'ザンビア', '잠비아', 'Zambia', 'แซมเบีย', '尚比亞', 'زامبيا', 'Zambia']),
  ('ZW', '🇿🇼', ['Zimbabwe', 'Zimbabve', 'Zimbabue', 'Zimbábue', 'Simbabwe', 'Zimbabwe', 'Zimbabwe', 'Зимбабве', 'ジンバブエ', '짐바브웨', 'Zimbabwe', 'ซิมบับเว', '辛巴威', 'زيمبابوي', 'Zimbabwe']),
];

int _langIndex(String lang) {
  final i = kCountryLangOrder.indexOf(lang);
  return i == -1 ? kCountryLangOrder.indexOf('en') : i;
}

String countryName(CountryData c, String lang) => c.$3[_langIndex(lang)];

String countryDisplay(CountryData c, String lang) =>
    '${c.$2} ${countryName(c, lang)}';

CountryData countryByCode(String code) =>
    kCountries.firstWhere((c) => c.$1 == code, orElse: () => kCountries.firstWhere((c) => c.$1 == 'TR'));
